<?php include('templates/header.php') ?>
<?php include('templates/header-nav-no-current.php') ?>
	<div class="container">		
		<!-- Row of columns -->
		<div class="row">
			<?php include('templates/navigation.php') ?>
				<!-- Main Content -->
				<div class="span9">
							<h3>Accepting the Terms of Service</h3>
							<p>The purpose of this app is to engage friends in fun activities using memes. Please read these terms of service ("Agreement") carefully before using the application or any services provided on the application (collectively, "Services"). By using or accessing the Services, you agree to become bound by all the terms and conditions of this Agreement. If you do not agree to all the terms and conditions of this Agreement, do not use the Services. The Services are accessed by You (User or You) under the following terms and conditions:</p>
							<h4>1. Access to the Services</h4>
							<p>Subject to the terms and conditions of this Agreement, memify may offer to provide the Services, as described more fully on the application, and which are selected by User, solely for User's own use, and not for the use or benefit of any third party. Services shall include, but not be limited to, any services memify performs for User, as well as the offering of any Content (as defined below) on the application. Memify may change, suspend or discontinue the Services at any time, including the availability of any feature, database, or Content. Memify may also impose limits on certain features and services or restrict User's access to parts or all of the Services without notice or liability. Memify reserves the right, at its discretion, to modify these Terms of Service at any time by posting revised Terms of Service on the application and by providing notice via e-mail, where possible, or on the application. User shall be responsible for reviewing and becoming familiar with any such modifications. Use of the Services by User following such modification constitutes User's acceptance of the terms and conditions of this Agreement as modified.</p>
							<p>User certifies to memify that if User is an individual (i.e., not a corporate entity), User is at least 13 years of age. No one under the age of 13 may provide any personal information to or on memify (including, for example, a name, address, telephone number or email address). User also certifies that it is legally permitted to use the Services and access the application, and takes full responsibility for the selection and use of the Services and access of the application. This Agreement is void where prohibited by law, and the right to access the application is revoked in such jurisdictions. Memify makes no claim that the application may be lawfully viewed or that Content may be downloaded outside of the United States. Access to the Content may not be legal by certain persons or in certain countries. If You access the application from outside the United States, You do so at Your own risk and You are responsible for compliance with the laws of Your jurisdiction.</p>
							<p>Memify will use reasonable efforts to ensure that the application and Services are available twenty-four hours a day, seven days a week. However, there will be occasions when the application and/or Services will be interrupted for maintenance, upgrades and repairs or due to failure of telecommunications links and equipment. Every reasonable step will be taken by memify to minimize such disruption where it is within memify's reasonable control.</p>
							<p>Memify has the right to discontinue service to any User at any time for acts deemed undesirable.</p>
							<p>User shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access the application or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. User shall be responsible for ensuring that such equipment or ancillary services are compatible with the Services.</p>
							<h4>2. Application Content</h4>
							<p>The application and its contents are intended solely for the use of memify users and may only be used in accordance with the terms of this agreement. All materials displayed or performed on the application, including, but not limited to text, graphics, logos, tools, photographs, images, illustrations, software or source code, audio and video, animations and themes are the property of memify and/or third parties and are protected by United States and international copyright laws. All trademarks, service marks, and trade names are proprietary to memify and/or third parties. User shall abide by all copyright notices, information, and restrictions contained in any Content accessed through the Services.</p>
							<p>User may download or copy the Content, and other items displayed on the application for download, for personal use only, provided that User maintains all copyright and other notices contained in such Content. Downloading, copying, or storing any Content for other than personal, noncommercial use is expressly prohibited without prior written permission from memify, or from the copyright holder identified in such Content's copyright notice. In the event You download software from the application, the software, including any files, images incorporated in or generated by the software, and the data accompanying the software (collectively, the "Software") is licensed to You by memify or third party licensors for Your personal, noncommercial use, and no title to the Software shall be transferred to You. You may own the User Content on which the Software is recorded, but memify or third party licensors retain full and complete title to the Software and all intellectual property rights therein.</p>
							<h4>3. User Content</h4>
							<p>User shall own all User Content that User contributes to the application, but hereby grants and agrees to grant memify a non-exclusive, worldwide, royalty-free, transferable right and license (with the right to sublicense), to use, copy, cache, publish, display, distribute, modify, create derivative works and store such User Content and to allow others to do so ("Content License") in order to provide the Services. User warrants, represents and agrees User has the right to grant memify and the application the rights set forth above. User represents, warrants and agrees that it will not contribute any User Content that (a) infringes, violates or otherwise interferes with any copyright or trademark of another party, (b) reveals any trade secret, unless User owns the trade secret or has the owner's permission to post it, (c) infringes any intellectual property right of another or the privacy or publicity rights of another, (d) is libelous, defamatory, abusive, threatening, harassing, hateful, offensive or otherwise violates any law or right of any third party, (e) contains a virus, Trojan horse, worm, time bomb or other computer programming routine or engine that is intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or information, or (f) remains posted after User has been notified that such User Content violates any of sections (a) to (e) of this sentence. memify reserves the right to remove any User Content from the application, suspend or terminate User's right to use the Services at any time, or pursue any other remedy or relief available to memify and/or the application under equity or law, for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such User Content or if memify is concerned that User may have breached the immediately preceding sentence), or for no reason at all.</p>
							<h4>4. Acceptable Content</h4>
							<p>The intent of this section is to clarify what we consider to be acceptable use of memify.</p>
							<p>If any content is found in violation of the following conditions it will be removoded from the application within 24 hours. If the infriengments on this content policy are repeated you will be banned from accessing the Create a Meme function. We will do our best to work with you and any parties involved to resolve issues in a timely manner. We reserve the right to immediately suspend, without notice, any content, account, or IP address which we determine to be systematically generated, spam, or potentially damaging to our service or infrastructure.</p>
							<p>The following condition are in violation of the Content Policy set forth by memify. If any content is found in violation of this policy set forth, it will be removed immidiatly</p>
							<ul>
								<li><span class="bold">Redundant Content.</span> memify is not intended to be a photo storage service or an all-purpose content aggregator. Users who abuse the import service or aggregate content in way deemed not acceptable by memify are likely to be suspended.</li>
								<li><span class="bold">Illegal Use.</span> memify may not be used for illegal purposes. </li>
								<li><span class="bold">Spam.</span> Users that do not publish meaningful content, use deceptive means to generate revenue or traffic, or whose primary purpose is affiliate marketing, will be suspended.</li>
								<li><span class="bold">Identity Theft and Privacy.</span> Users that misleadingly appropriate the identity of another person are not permitted. Users may not post other people's personally identifying or confidential information, including but not limited to credit card numbers, Social Security Numbers, and driver's and other license numbers. You may not post information such as other people's passwords, usernames, phone numbers, addresses and e-mail addresses unless already publicly accessible on the Web.</li>
								<li><span class="bold">Hate Content, Defamation, and Libel.</span> Hate speech and other objectionable content that is unlawful, defamatory, and fraudulent. </li>
								<li><span class="bold">Disruptions and Exploits.</span> We will terminate accounts and block addresses of those who attempt unauthorized use of memify application.</li>
								<li><span class="bold">Copyright.</span> Using copyrighted material does not constitute infringement in all cases. In general, however, users should  not use copyrighted content without the permission of those who created it. It is our policy to respond to notices of alleged infringement that comply with the Digital Millennium Copyright Act ("DMCA").</li>
								<li><span class="bold">Sexually Explicit Content.</span> Any pictures deemed sexually explicit.</li>
							</ul>
							<h4>5. Restrictions</h4>
							<p>User is responsible for all of its activity in connection with the Services and accessing the application. Any fraudulent, abusive, or otherwise illegal activity or any use of the Services or Content in violation of this Agreement may be grounds for termination of User's right to Services or to access the application. User may not post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain password, account, or private information from any memify user.</p>
							<p>Use of the application or Services to violate the security of any computer network, crack passwords or security encryption codes, transfer or store illegal material including that are deemed threatening or obscene, or engage in any kind of illegal activity is expressly prohibited. Under no circumstances will User use the application or the Service to (a) send unsolicited e-mails, bulk mail, spam or other materials to Users of the application or any other individual, (b) harass, threaten, stalk or abuse any person or party, including other Users of the application, (c) create a false identity or to impersonate another person, or (d) post any false, inaccurate or incomplete material or delete or revise any material that was not posted by You.</p>
							<h4>6. Warranty Disclaimer</h4>
							<p>Memify has no special relationship with or fiduciary duty to User. User acknowledges that memify has no control over, and no duty to take any action regarding: which Users gains access to the application; which Content User accesses via the application; what effects the Content may have on User; how User may interpret or use the Content; or what actions User may take as a result of having been exposed to the Content. Much of the Content of the application is provided by and is the responsibility of the User or User who posted the Content. memify does not monitor the Content of the application and takes no responsibility for such Content. User releases memify from all liability for User having acquired or not acquired Content through the application. The application may contain, or direct User to sites containing, information that some people may find offensive or inappropriate. memify makes no representations concerning any content contained in or accessed through the application, and memify will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the application.</p>
							<p>Although memify and the application will make reasonable efforts to store and preserve the material residing on the application, neither memify nor the application is responsible or liable in any way for the failure to store, preserve or access User Content or other materials you transmit or archive on the application. You are strongly urged to take measures to preserve copies of any data, material, content or information you post or upload on the application. You are solely responsible for creating back-ups of your User Content.</p>
							<p>The Services, Content, application and any Software are provided on an "as is" basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose or non-infringement. memify makes no representations or warranties of any kind with respect to the application, the Services, including any representation or warranty that the use of the application or Services will (a) be timely, uninterrupted or error-free or operate in combination with any other hardware, software, system or data, (b) meet your requirements or expectations, (c) be free from errors or that defects will be corrected, (d) be free of viruses or other harmful components.</p>
							<p>To the fullest extent allowed by law, memify disclaims any liability or responsibility for the accuracy, reliability, availability, completeness, legality or operability of the material or services provided on this application. By using this application, you acknowledge that memify is not responsible or liable for any harm resulting from (1) use of the application; (2) downloading information contained on the application including but not limited to downloads of content posted by Users; (3) unauthorized disclosure of images, information or data that results from the upload, download or storage of content posted by Users; (4) the temporary or permanent inability to access or retrieve any User Content from the application, including, without limitation, harm caused by viruses, worms, Trojan horses, or any similar contamination or destructive program.</p>
							<p>Some states do not allow limitations on how long an implied warranty lasts, so the above limitations may not apply to User.</p>
							<h4>7. Third Party Websites</h4>
							<p>Users of the application may gain access from the application to third party sites on the Internet through hypertext or other computer links on the application. Third party sites are not within the supervision or control of memify or the application. Unless explicitly otherwise provided, neither memify nor the application make any representation or warranty whatsoever about any third party site that is linked to the application, or endorse the products or services offered on such site. Memify and the application disclaim: (a) all responsibility and liability for content on third party websites and (b) any representations or warranties as to the security of any information (including, without limitation, credit card and other personal information) You might be requested to give any third party, and You hereby irrevocably waive any claim against the application or memify with respect to such sites and third party content.</p>
							<h4>8. Registration and Security</h4>
							<p>As a condition to using Services, User will be required to Login with Facebook. Failure to do so shall constitute a breach of this Agreement. User may not impersonate that another individual. Memify reserves the right to refuse registration of, or cancel a memify URL in its discretion. User shall be responsible for maintaining the confidentiality of his login information. User is solely responsible for any use of or action taken under User's Facebook login and accepts full responsibility for all activity conducted through User's account and agrees to and hereby releases the application and memify from any and all liability concerning such activity. User agrees to notify memify immediately of any actual or suspected loss, theft, or unauthorized use of User's material. The application will take reasonable security precautions when using the internet, telephone or other means to transport data or other communications, but expressly disclaims any and all liability for the accessing of any such data communications by unauthorized persons or entities.</p>
							<h4>9. Indemnity</h4>
							<p>User will indemnify and hold memify, its directors, officers and employees, harmless, including costs and attorneys' fees, from any claim or demand made by any third party due to or arising out of User's access to the application, use of the Services, the violation of this Agreement by User, or the infringement by User, or any third party using the User's account, of any intellectual property or other right of any person or entity.</p>
							<h4>10. Limitation of Liability</h4>
							<p>In no event shall memify, its directors, officers, shareholders, employees or members be liable with respect to the application or the Services for (a) any indirect, incidental, punitive, or consequential damages of any kind whatsoever; (b) damages for loss of use, profits, data, images, User Content or other intangibles; (c) damages for unauthorized use, non-performance of the application, errors or omissions; or (d) damages related to downloading or posting Content. Memify's and the application's collective liability under this agreement shall be limited to three hundred United States Dollars. Some states do not allow the exclusion or limitation of incidental or consequential damages, so the above limitations and exclusions may not apply to User.</p>
							<h4>11. Termination</h4>
							<p>Either party may terminate the Services at any time by notifying the other party by any means. Memify may also terminate or suspend any and all Services and access to the application immediately, without prior notice or liability, if User breaches any of the terms or conditions of this Agreement. Upon termination of User's account, User's right to use the Services, access the application, and any Content will immediately cease. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability. Termination of Your access to and use of the application and the Services shall not relieve User of any obligations arising or accruing prior to such termination or limit any liability which User otherwise may have to memify or the application, including without limitation any indemnification obligations contained herein.
							<h4>12. Privacy</h4>
							<p>Please review our <a href="privacy.php"><u>Privacy Policy</u></a>, which governs the use of personal information on the application and to which User agrees to be bound as a User of the application.</p>
							<h4>13. Miscellaneous</h4>
							<p>This Agreement (including the <a href="privacy.php"><u>Privacy Policy</u></a>), as modified from time to time, constitutes the entire agreement between You, the application and memify with respect to the subject matter hereof. This Agreement replaces all prior or contemporaneous understandings or agreements, written or oral, regarding the subject matter hereof. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. Memify shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond memify's reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation. If any provision of this Agreement is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sublicensable by User except with memify's prior written consent. Memify may assign this Agreement in whole or in part at any time without user's consent. This Agreement shall be governed by and construed in accordance with the laws of the state of Delaware without regard to the conflict of laws provisions thereof. No agency, partnership, joint venture, or employment is created as a result of this Agreement and User does not have any authority of any kind to bind memify in any respect whatsoever. </p>
				</div> <!-- end of span9 -->	
		</div> <!-- end of row -->
<?php include('templates/footer.php') ?>